set quiet

setup:
    pnpm install

build: setup
    pnpm build

run: setup
    pnpm dev

test:
    pnpm test

test-watch:
    pnpm test:watch

format:
    pnpm format

lint:
    pnpm lint

clean:
    rm -rf node_modules dist
